### ISSUE TITLE
Priority2.2 acceses wall

### ISSUE THREAD

**Issue by hassam196** [sduoase/STAR_DICES#23]
As a writer
I want to to access my wall
So that I can see my stories and my stats(e.g., #/avg/ratio of likes/dislikes, avg dice per story, ...)
Priority2.2

**Comment by sduoase** [comment]
Stats are missing.

**Comment by Alepacox** [comment]
I think to a simple formula to calculate the stats, like (#ofLikesReceived/#ofDislikesReceived)/#ofposts.
What do you think about that?

**Comment by sduoase** [comment]
> I think to a simple formula to calculate the stats, like (#ofLikesReceived/#ofDislikesReceived)/#ofposts.
> What do you think about that?

Sure, we can go for that.

Anyway I suggest to do the math for each stat we want to show in a specific function, so that if we want to change how the stat is obtained we only need to write a new function and call that (instead of the old oen).
