### ISSUE TITLE
Priority 1.7: see list of all stories

### ISSUE THREAD

**Issue by BNRABAA** [sduoase/STAR_DICES#24]
As a reader 

I want to see list of all stories 

So that I can read them 

Priority1.7

**Comment by Alepacox** [comment]
Do you think we should limit the number of character displayed per story in this specific API?

**Comment by sduoase** [comment]
I think so.

**Comment by Alepacox** [comment]
Related to https://github.com/sduoase/STAR_DICES/pull/44
