### ISSUE TITLE
Priority 1.8: open a story

### ISSUE THREAD

**Issue by BNRABAA** [sduoase/STAR_DICES#26]
As a reader 

I want to open a story 

So that I can see all info about it (dice roll, (dis)likes...) 

Priority1.8

**Comment by sduoase** [comment]
See https://github.com/sduoase/STAR_DICES/pull/41.

(Dice roll are missing)

**Comment by sduoase** [comment]
Dice roll are missing.

**Comment by Gr3gbug** [comment]
See https://github.com/sduoase/STAR_DICES/pull/70.

**Comment by nicolotonci** [comment]
Is this resolved?

**Comment by Alepacox** [comment]
> Is this resolved?

Yes
