### ISSUE TITLE
Priority 1.9: add dislike to a story 

### ISSUE THREAD

**Issue by BNRABAA** [sduoase/STAR_DICES#30]
Asa reader

I want to add my dislike to a story 

So that I can be social 

Priority1.9

**Comment by sduoase** [comment]
see [https://github.com/sduoase/STAR_DICES/issues/28#issuecomment-546288369](like issue comment)

**Comment by sduoase** [comment]
See https://github.com/sduoase/STAR_DICES/pull/53.
