### ISSUE TITLE
/home restyling and proposal for new /explore api

### ISSUE THREAD

**Issue by Alepacox** [sduoase/STAR_DICES#65]
In order to implement https://github.com/sduoase/STAR_DICES/issues/21 and thinking about the fact that the user should be able to:
- view the stories of the following writers 
- view all the stories

I was thinking about separating the scopes. In the /home we will have two views:
- one that propose the top X stories depending on some ranking
- one with the recent stories of the following writers.

Then, creating a new api, called /explore, where the user can browse all the possible stories in the social network.

**Comment by sduoase** [comment]
👍🏻

**Comment by nicolotonci** [comment]
Implemented! Closing this issue!

**Comment by sduoase** [comment]
See https://github.com/sduoase/STAR_DICES/pull/76.
