### ISSUE TITLE
priority 2.1 check if story is valid

### ISSUE THREAD

**Issue by hassam196** [sduoase/STAR_DICES#7]
As a writer
I want to the app to check whether my story is valid
So that I can post only valid stories
Priority2.1

**Comment by sduoase** [comment]
Must wait for https://github.com/sduoase/STAR_DICES/issues/20 to be ready.

**Comment by sduoase** [comment]
See https://github.com/sduoase/STAR_DICES/pull/59 (helper function ready).

**Comment by sduoase** [comment]
We only need to use the helper function during a POST to publish a story.

**Comment by Gr3gbug** [comment]
See https://github.com/sduoase/STAR_DICES/pull/68.
